//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advices()
        {
            this.AdvicesProducts = new HashSet<AdvicesProducts>();
        }
    
        public long PkIdentifier { get; set; }
        public string FkUsers_Merchant_Identifier { get; set; }
        public string FkUsers_Manufacturer_Identifier { get; set; }
        public string AdviceNumber { get; set; }
        public bool ManualAdvise { get; set; }
        public string Orders_OrderNumber { get; set; }
        public string FkCentres_Identifier { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
    
        public virtual Centres Centres { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvicesProducts> AdvicesProducts { get; set; }
    }
}
