//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockCalendar
    {
        public long PkIdentifier { get; set; }
        public string FkUsers_Merchant_Identifier { get; set; }
        public string FkCentres_Identifier { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> Dock { get; set; }
        public bool GeneralRuleToApply { get; set; }
        public string FkBlockingReasons_Identifier { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public string FkUsers_Creator_Identifier { get; set; }
    
        public virtual BlockingReasons BlockingReasons { get; set; }
        public virtual Centres Centres { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
