//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Centres()
        {
            this.Advices = new HashSet<Advices>();
            this.BlockCalendar = new HashSet<BlockCalendar>();
            this.LinkedCentres = new HashSet<LinkedCentres>();
            this.UnloadingTime = new HashSet<UnloadingTime>();
        }
    
        public string FkUsers_Merchant_Identifier { get; set; }
        public string FkUsers_Responsable_Identifier { get; set; }
        public string PkIdentifier { get; set; }
        public Nullable<int> WeeklyCapacity { get; set; }
        public Nullable<int> CurrentWeekCapacity { get; set; }
        public string FirstDay { get; set; }
        public string ListOfWorkingDays { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Name { get; set; }
        public Nullable<short> NumberOfDocks { get; set; }
        public Nullable<int> TimeBetweenSuppliers { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public long FkTimezones_Identifier { get; set; }
        public string AddressStreet { get; set; }
        public string AddressNumber { get; set; }
        public string PostCode { get; set; }
        public string Town { get; set; }
        public string Region { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advices> Advices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockCalendar> BlockCalendar { get; set; }
        public virtual Timezones Timezones { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedCentres> LinkedCentres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnloadingTime> UnloadingTime { get; set; }
    }
}
