//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedProducts
    {
        public long PkIdentifier { get; set; }
        public string FkUsers_Identifier { get; set; }
        public string ProductCode { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
