//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advices> Advices { get; set; }
        public virtual DbSet<AdvicesProducts> AdvicesProducts { get; set; }
        public virtual DbSet<BlockCalendar> BlockCalendar { get; set; }
        public virtual DbSet<BlockingReasons> BlockingReasons { get; set; }
        public virtual DbSet<Centres> Centres { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<LinkedCentres> LinkedCentres { get; set; }
        public virtual DbSet<LinkedProducts> LinkedProducts { get; set; }
        public virtual DbSet<LinkedUsers> LinkedUsers { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersProducts> OrdersProducts { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Timezones> Timezones { get; set; }
        public virtual DbSet<Turns> Turns { get; set; }
        public virtual DbSet<TurnsProducts> TurnsProducts { get; set; }
        public virtual DbSet<TurnsStatus> TurnsStatus { get; set; }
        public virtual DbSet<UnloadingTime> UnloadingTime { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
