//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersProducts = new HashSet<OrdersProducts>();
        }
    
        public long PkIdentifier { get; set; }
        public string FkUsers_Merchant_Identifier { get; set; }
        public string FkUsers_Manufacturer_Identifier { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> MaxDeliveryDate { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> FkStatus_Identifier { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersProducts> OrdersProducts { get; set; }
    }
}
