//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersProducts
    {
        public long PkIdentifier { get; set; }
        public Nullable<long> FkOrders_Identifier { get; set; }
        public Nullable<int> Line { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<long> SplitQuantity { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
