//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turns()
        {
            this.TurnsProducts = new HashSet<TurnsProducts>();
        }
    
        public long PkIdentifier { get; set; }
        public string FkUsers_Merchant_Identifier { get; set; }
        public string FkUsers_Manufacturer_Identifier { get; set; }
        public string FkUsers_Requester_Identifier { get; set; }
        public string FkUsers_Modifier_Identifier { get; set; }
        public string Orders_OrderNumber { get; set; }
        public string ReceivingAdvice_ReceivingAdviceNumber { get; set; }
        public Nullable<short> Dock { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> FixedTime { get; set; }
        public Nullable<System.DateTime> VariableTime { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public string FkTurnsStatus_Identifier { get; set; }
    
        public virtual TurnsStatus TurnsStatus { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Users Users3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnsProducts> TurnsProducts { get; set; }
    }
}
