//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Shifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnloadingTime
    {
        public long PkIdentifier { get; set; }
        public string FkCentres_Identifier { get; set; }
        public string FkUsers_Manufacturer_Identifier { get; set; }
        public string ProductCode { get; set; }
        public string MeasureUnit { get; set; }
        public Nullable<short> Dock { get; set; }
        public Nullable<decimal> AmountPerPallet { get; set; }
        public Nullable<int> SpecificUnloadingTime { get; set; }
        public string PalletType { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
    
        public virtual Centres Centres { get; set; }
        public virtual Companies Companies { get; set; }
    }
}
