//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carvajal.Turns.CodeResponses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carvajal.Turns.CodeResponses.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el metodo.
        /// </summary>
        public static string A0 {
            get {
                return ResourceManager.GetString("A0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Ejecucion de Archivos Maestros: EDI y CSV. Comercio: .
        /// </summary>
        public static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presento problemas con los datos obligatorios suministrados..
        /// </summary>
        public static string A10 {
            get {
                return ResourceManager.GetString("A10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generaron inconvenientes en el procesamiento del Aviso del archivo: .
        /// </summary>
        public static string A11 {
            get {
                return ResourceManager.GetString("A11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error  durante el guarde de la Orden:.
        /// </summary>
        public static string A12 {
            get {
                return ResourceManager.GetString("A12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al borrar el Fabricante:.
        /// </summary>
        public static string A13 {
            get {
                return ResourceManager.GetString("A13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generaron inconvenientes en el procesamiento del Fabricante del archivo:.
        /// </summary>
        public static string A14 {
            get {
                return ResourceManager.GetString("A14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de guardar usuario Fabricante:.
        /// </summary>
        public static string A15 {
            get {
                return ResourceManager.GetString("A15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al durante el guarde de elemento Fabricante: .
        /// </summary>
        public static string A16 {
            get {
                return ResourceManager.GetString("A16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generaron inconvenientes en el procesamiento del Comercio del archivo:.
        /// </summary>
        public static string A17 {
            get {
                return ResourceManager.GetString("A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de guardar usuario Fabricante:.
        /// </summary>
        public static string A18 {
            get {
                return ResourceManager.GetString("A18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al durante el guarde de elemento Fabricante:.
        /// </summary>
        public static string A19 {
            get {
                return ResourceManager.GetString("A19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo .
        /// </summary>
        public static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no ha tiene una extension reconocible (EDI o CSV) y sera omitido..
        /// </summary>
        public static string A2_1 {
            get {
                return ResourceManager.GetString("A2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generaron inconvenientes en el procesamiento de Centros de Entrega del archivo:.
        /// </summary>
        public static string A20 {
            get {
                return ResourceManager.GetString("A20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generaron inconvenientes en el procesamiento de Centros de Entrega del archivo:.
        /// </summary>
        public static string A21 {
            get {
                return ResourceManager.GetString("A21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de guardar Centro de Entrega:.
        /// </summary>
        public static string A22 {
            get {
                return ResourceManager.GetString("A22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al durante el guarde de elemento Centro de Entrega:.
        /// </summary>
        public static string A23 {
            get {
                return ResourceManager.GetString("A23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generaron inconvenientes en el procesamiento de Tiempos de Descarga del archivo:.
        /// </summary>
        public static string A24 {
            get {
                return ResourceManager.GetString("A24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se generaron inconvenientes en el procesamiento del Tiempos de Descarga del archivo:.
        /// </summary>
        public static string A25 {
            get {
                return ResourceManager.GetString("A25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de guardar Tiempos de Descarga: .
        /// </summary>
        public static string A26 {
            get {
                return ResourceManager.GetString("A26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al durante el guarde de elemento Tiempos de Descarga: .
        /// </summary>
        public static string A27 {
            get {
                return ResourceManager.GetString("A27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe las carpetas para ese comercio: .
        /// </summary>
        public static string A28 {
            get {
                return ResourceManager.GetString("A28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de Ejecucion de Archivos Maestros: EDI y CSV. Comercio:.
        /// </summary>
        public static string A29 {
            get {
                return ResourceManager.GetString("A29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo {0}  ha sido cargado al sistema y tiene firma MD5 {1}..
        /// </summary>
        public static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ha sido cargado al sistema y tiene firma MD5: .
        /// </summary>
        public static string A3_1 {
            get {
                return ResourceManager.GetString("A3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al borrar el Usuario Administrador / Operador: .
        /// </summary>
        public static string A30 {
            get {
                return ResourceManager.GetString("A30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al borrar el Centro de Entrega:.
        /// </summary>
        public static string A31 {
            get {
                return ResourceManager.GetString("A31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  fue subido exitosamente a la carpeta Procesados y fue guardado exitosamente..
        /// </summary>
        public static string A32 {
            get {
                return ResourceManager.GetString("A32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra la zona horaria .
        /// </summary>
        public static string A33 {
            get {
                return ResourceManager.GetString("A33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  para el centro:.
        /// </summary>
        public static string A33_1 {
            get {
                return ResourceManager.GetString("A33_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  fue eliminado exitosamente a la carpeta SinProcesar.
        /// </summary>
        public static string A34 {
            get {
                return ResourceManager.GetString("A34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  no fue eliminado de la carpeta SinProcesar.
        /// </summary>
        public static string A35 {
            get {
                return ResourceManager.GetString("A35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible guardar la informacion del archivo: .
        /// </summary>
        public static string A36 {
            get {
                return ResourceManager.GetString("A36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo no fue Subido exitosamente a la carpeta Procesados: .
        /// </summary>
        public static string A37 {
            get {
                return ResourceManager.GetString("A37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error durante la ejecucion de de ejecucion orden de ProcessOrder: .
        /// </summary>
        public static string A38 {
            get {
                return ResourceManager.GetString("A38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede iniciar el flujo general. Excepcion: .
        /// </summary>
        public static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le faltan campos obligatorios EDI, ejemplo BGM, NAD, UNZ..
        /// </summary>
        public static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presento error durante la lectura del archivo:.
        /// </summary>
        public static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de guardar productos del Aviso:.
        /// </summary>
        public static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de guardar productos de la Orden:.
        /// </summary>
        public static string A8 {
            get {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error  durante el guarde del Aviso:.
        /// </summary>
        public static string A9 {
            get {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico ingresado ya se encuentra registrado para otro usuario.
        /// </summary>
        public static string M38 {
            get {
                return ResourceManager.GetString("M38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo .
        /// </summary>
        public static string M45 {
            get {
                return ResourceManager.GetString("M45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  no cumple con la estructura definida.
        /// </summary>
        public static string M45_1 {
            get {
                return ResourceManager.GetString("M45_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La extensión del archivo no es .csv.
        /// </summary>
        public static string M46 {
            get {
                return ResourceManager.GetString("M46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo: .
        /// </summary>
        public static string M47 {
            get {
                return ResourceManager.GetString("M47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es obligatorio.
        /// </summary>
        public static string M47_1 {
            get {
                return ResourceManager.GetString("M47_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo: .
        /// </summary>
        public static string M48 {
            get {
                return ResourceManager.GetString("M48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falta.  No queda completa su funcionalidad..
        /// </summary>
        public static string M48_1 {
            get {
                return ResourceManager.GetString("M48_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo: .
        /// </summary>
        public static string M49 {
            get {
                return ResourceManager.GetString("M49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  excede el tamaño permitido.
        /// </summary>
        public static string M49_1 {
            get {
                return ResourceManager.GetString("M49_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo: .
        /// </summary>
        public static string M50 {
            get {
                return ResourceManager.GetString("M50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  tiene caracteres no permitidos.
        /// </summary>
        public static string M50_1 {
            get {
                return ResourceManager.GetString("M50_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cargaron .
        /// </summary>
        public static string M51 {
            get {
                return ResourceManager.GetString("M51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  con éxito.
        /// </summary>
        public static string M51_1 {
            get {
                return ResourceManager.GetString("M51_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor .
        /// </summary>
        public static string M52 {
            get {
                return ResourceManager.GetString("M52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ya se encuentra registrado, se realiza la modificación de la información.
        /// </summary>
        public static string M52_1 {
            get {
                return ResourceManager.GetString("M52_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto .
        /// </summary>
        public static string M53 {
            get {
                return ResourceManager.GetString("M53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya se encuentra registrado, se realiza la modificación de la información.
        /// </summary>
        public static string M53_1 {
            get {
                return ResourceManager.GetString("M53_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto .
        /// </summary>
        public static string M54 {
            get {
                return ResourceManager.GetString("M54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya se encuentra registrado y la información de proveedor es diferente, no se realiza la modificación.
        /// </summary>
        public static string M54_1 {
            get {
                return ResourceManager.GetString("M54_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario .
        /// </summary>
        public static string M55 {
            get {
                return ResourceManager.GetString("M55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya se encuentra registrado, se realiza la modificación de la información.
        /// </summary>
        public static string M55_1 {
            get {
                return ResourceManager.GetString("M55_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor .
        /// </summary>
        public static string M56 {
            get {
                return ResourceManager.GetString("M56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya se encuentra registrado por otro comercio, no se realiza la modificación de la información.
        /// </summary>
        public static string M56_1 {
            get {
                return ResourceManager.GetString("M56_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El centro de entrega .
        /// </summary>
        public static string M57 {
            get {
                return ResourceManager.GetString("M57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya se encuentra registrado, se realiza la modificación de la información.
        /// </summary>
        public static string M57_1 {
            get {
                return ResourceManager.GetString("M57_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para la orden de compra .
        /// </summary>
        public static string M58 {
            get {
                return ResourceManager.GetString("M58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el proveedor.
        /// </summary>
        public static string M58_1 {
            get {
                return ResourceManager.GetString("M58_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encuentra registrado.
        /// </summary>
        public static string M58_2 {
            get {
                return ResourceManager.GetString("M58_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para la orden de compra .
        /// </summary>
        public static string M59 {
            get {
                return ResourceManager.GetString("M59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el centro de entrega .
        /// </summary>
        public static string M59_1 {
            get {
                return ResourceManager.GetString("M59_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encuentra registrado.
        /// </summary>
        public static string M59_2 {
            get {
                return ResourceManager.GetString("M59_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden de compra .
        /// </summary>
        public static string M60 {
            get {
                return ResourceManager.GetString("M60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ya se encuentra registrada en el estado.
        /// </summary>
        public static string M60_1 {
            get {
                return ResourceManager.GetString("M60_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para la orden de compra .
        /// </summary>
        public static string M61 {
            get {
                return ResourceManager.GetString("M61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el comercio .
        /// </summary>
        public static string M61_1 {
            get {
                return ResourceManager.GetString("M61_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encuentra registrado.
        /// </summary>
        public static string M61_2 {
            get {
                return ResourceManager.GetString("M61_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para la orden de compra .
        /// </summary>
        public static string M62 {
            get {
                return ResourceManager.GetString("M62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no tiene un turno agendado.
        /// </summary>
        public static string M62_1 {
            get {
                return ResourceManager.GetString("M62_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para la orden de compra .
        /// </summary>
        public static string M63 {
            get {
                return ResourceManager.GetString("M63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to las fechas del RECDV es menor.
        /// </summary>
        public static string M63_1 {
            get {
                return ResourceManager.GetString("M63_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La extensión del archivo no es .edi.
        /// </summary>
        public static string M64 {
            get {
                return ResourceManager.GetString("M64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede convertir el archivo: .
        /// </summary>
        public static string M65 {
            get {
                return ResourceManager.GetString("M65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  se encontraron menos campos de los esperados:.
        /// </summary>
        public static string M65_1 {
            get {
                return ResourceManager.GetString("M65_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la orden .
        /// </summary>
        public static string M66 {
            get {
                return ResourceManager.GetString("M66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para el Aviso.
        /// </summary>
        public static string M66_1 {
            get {
                return ResourceManager.GetString("M66_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para el aviso.
        /// </summary>
        public static string M67 {
            get {
                return ResourceManager.GetString("M67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el comercio.
        /// </summary>
        public static string M67_1 {
            get {
                return ResourceManager.GetString("M67_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encuentra registrado.
        /// </summary>
        public static string M67_2 {
            get {
                return ResourceManager.GetString("M67_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para el aviso.
        /// </summary>
        public static string M68 {
            get {
                return ResourceManager.GetString("M68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  el centro.
        /// </summary>
        public static string M68_1 {
            get {
                return ResourceManager.GetString("M68_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encuentra registrado.
        /// </summary>
        public static string M68_2 {
            get {
                return ResourceManager.GetString("M68_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para la orden.
        /// </summary>
        public static string M69 {
            get {
                return ResourceManager.GetString("M69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electronico esta errado:.
        /// </summary>
        public static string M70 {
            get {
                return ResourceManager.GetString("M70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el comercio registrado:.
        /// </summary>
        public static string M71 {
            get {
                return ResourceManager.GetString("M71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario  Administrador / Operador con el mismo Identificador de este Fabricante: .
        /// </summary>
        public static string M72 {
            get {
                return ResourceManager.GetString("M72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario  Administrador / Operador con el mismo Identificador:.
        /// </summary>
        public static string M73 {
            get {
                return ResourceManager.GetString("M73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario  Comerciante / Fabricante con el mismo Identificador:.
        /// </summary>
        public static string M74 {
            get {
                return ResourceManager.GetString("M74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el centro de entrega registrado: .
        /// </summary>
        public static string M75 {
            get {
                return ResourceManager.GetString("M75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para el comercio registrado: .
        /// </summary>
        public static string M76 {
            get {
                return ResourceManager.GetString("M76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el fabricante registrado:.
        /// </summary>
        public static string M77 {
            get {
                return ResourceManager.GetString("M77", resourceCulture);
            }
        }
    }
}
